import { cn } from "@/lib/utils";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/navbar/navbar";

export const metadata: Metadata = {
	title: "Hana - Next.js ecommerce",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					"min-h-screen antialiased bg-background",
					GeistSans.className,
				)}
			>
				<Navbar />
				<main className="px-5 2xl:px-0">{children}</main>
				<footer>footer bar</footer>
			</body>
		</html>
	);
}
